language: python
services:
- postgresql
script:
- echo 0
deploy:
  provider: heroku
  api_key:
    secure: yTFyzBgpQNeZ705RKYOM0c2ZWC/Bn6jW7YK9bSOV9Kw0F4h+NOxo0siBm+J4kmO9gLTANfo3aAQoogQ5ugT/EprS1mKuGM3NGLfoIqCzVBMXOkq0N+LKbNFmUj7LFO9T+awl+00+vkvXP1W3mKIGuXBUE6rcBCgizzNE9sdal13OHpQDoUQyYDSAyKA/CFJB3KKhqB5Nq2TKqEYg4S0OuT3+l+lO/mXqoMH19ehacYp/hkn21zviy0pkLJAGgvDCrXwIYiPG7cCMp00UhltYPsJKwZ4haRfUcJNc5FwEsAD3OmgyR6wXNGK8I/TMXOimLYejVRoIOMAweBYkJX37OE0XFCi9hvDcin3PpCq0sR53Tea3NUBjYBEO5ci7EBCnc0pFbAWqx7/wXdFMwhFH3nG+aBwlrK/nMuZRA9efKnxal8vVLuwuhSY76GHdYuj37oSRo3W9NikMK5fosL8caurqCFM8kvToQkf/uNAiwZgRPq+3w7KOaKKX/7gEmol00M8g1cstsBwd3IXq+1wX3JVjDt2T+JTJFCAQ3kCukQHT6Ndxd2KDGkasPaMhBeBjxFvBq9FF1gm1S3wma0g9PXGZLYhthZeKChyDSXHOf1KpkbV/7Sy/sC6Gng0um27iCI+SZGNEqDuvfKrgumh87G56Nwl861BzvC1uopKulUA=
  app: cagriazcan
