language: python
services:
- postgresql
script:
- echo 0
deploy:
  provider: heroku
  api_key:
    secure: MBT4k98ryHk5uw1jlrG9GNNGIO1lcPfd2r06ijgN5k19+kr6eG/WyrFz/8pvMdP0EOREmPNcl0C9uJb81WzxDP4zXRN8HwGL2BSEUkLaqCkpX9U9LKxKJ34Vopdetss5x38icTrVUqB4z0hQdOBpt/a6RJ7xTdCoSkHBhSo8+/jted3PQLHDuEdVWMyVY/Izfy7bbxi4bTvzHiuDynWu7zAeyop9H5FOaI99TJfaCZ0tjtk8qaA37Pm6VVhmCCywCy83n+mifhK1srtmBPVtC+rtUDsq3Ik2lzmlTM0Wv2rjbTjHc8/RmGSMgvQEmdBEWurp/P1rGfMd7Kyf8HwFoBZjm/XU7CFh6eNSk8rwMvIf5HEQ1ov3KUA360BbV5lJjNLl1n0KEjvIb07IvIzfKGGlA+DXoG42cCXbVvSP05q/py3jZOMPbfojS+bAu1xDGI0OU+5Jk21Piy6ivs6v5ZMdmd5ws3T1gz3+afrtNqMjTwwHBGu72BRBlEDXwFAcbcfLkLzDqVBghgILy34GLDwlRC27IuOPfU0lqnN0M4eRtpvAlxKG7FWmfNUMPHalnUwStkCSQII4BMZoXQpi2ja482RHSvUHXVtoE7gyH3Jw7U9QIDRdrnl+sEXD7opDAZEfInNcmxwUvL58lJBxI0jyvQWZogfogIQ2HZ00n+Q=
  app: chipakraken
